services:
  - type: web
    name: sandelys
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeployTrigger: commit
    healthCheckPath: /login

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5

      - key: SECRET_KEY
        generateValue: true

      - key: DB_PATH
        value: database.db

      - key: BACKUP_DIR
        value: backups

      - key: DEFAULT_ADMIN_USERNAME
        sync: false

      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
